// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// nearest_neighbors_gpu
NumericMatrix nearest_neighbors_gpu(arma::mat locs, int m);
RcppExport SEXP _VecchiaNN_nearest_neighbors_gpu(SEXP locsSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type locs(locsSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(nearest_neighbors_gpu(locs, m));
    return rcpp_result_gen;
END_RCPP
}
// nearest_neighbors_sing_gpu
NumericMatrix nearest_neighbors_sing_gpu(arma::mat locs, int m, int nq);
RcppExport SEXP _VecchiaNN_nearest_neighbors_sing_gpu(SEXP locsSEXP, SEXP mSEXP, SEXP nqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type locs(locsSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type nq(nqSEXP);
    rcpp_result_gen = Rcpp::wrap(nearest_neighbors_sing_gpu(locs, m, nq));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_VecchiaNN_nearest_neighbors_gpu", (DL_FUNC) &_VecchiaNN_nearest_neighbors_gpu, 2},
    {"_VecchiaNN_nearest_neighbors_sing_gpu", (DL_FUNC) &_VecchiaNN_nearest_neighbors_sing_gpu, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_VecchiaNN(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
