# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nearest_neighbors_gpu <- function(locs, m) {
    .Call(`_VecchiaNN_nearest_neighbors_gpu`, locs, m)
}

nearest_neighbors_sing_gpu <- function(locs, m, nq) {
    .Call(`_VecchiaNN_nearest_neighbors_sing_gpu`, locs, m, nq)
}

