# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Nearest neighbors with ordering (double precision)
#'
#' From a matrix of locations and number of neighbors \code{m}
#' return the matrix of the nearest \code{m} locations that
#' appear earlier in the ordering
#' @param locs A matrix with \code{n} rows and \code{d} columns.
#' Each row of locs is a point in R^d.
#' @param m the Number of neighbors
#' @return A matrix with \code{n} rows and \code{m+1} columns, with row
#' i containing the indicies of the \code{m+1} locations closest to
#' observation i that appear earlier in the ordering
#' @export
nearest_neighbors_gpu <- function(locs, m) {
    .Call('_VecchiaNN_nearest_neighbors_gpu', PACKAGE = 'VecchiaNN', locs, m)
}

#' Nearest neighbors with ordering (single precision)
#'
#' From a matrix of locations and number of neighbors \code{m}
#' return the matrix of the nearest \code{m} locations that
#' appear earlier in the ordering
#' @param locs A matrix with \code{n} rows and \code{d} columns.
#' Each row of locs is a point in R^d.
#' @param m the Number of neighbors
#' @return A matrix with \code{n} rows and \code{m+1} columns, with row
#' i containing the indicies of the \code{m+1} locations closest to
#' observation i that appear earlier in the ordering
#' @export
nearest_neighbors_gpu_single <- function(locs, m) {
    .Call('_VecchiaNN_nearest_neighbors_gpu_single', PACKAGE = 'VecchiaNN', locs, m)
}

